version: "3.9"

services:
  php:
    image: php:8.2-fpm # เลือกเวอร์ชัน PHP ที่คุณต้องการ
    volumes:
      - ./src:/var/www/html # Mount โค้ด PHP ของคุณจากโฟลเดอร์ 'app' ในเครื่องโฮสต์
    networks:
      - appnet  
    # ถ้าคุณต้องการติดตั้ง Composer หรือ Dependency อื่นๆ คุณสามารถเพิ่มคำสั่งใน Dockerfile หรือใช้ entrypoint ได้
  web:
    image: nginx:latest # ใช้ Nginx เป็น Web server
    ports:
      - "80:80" # เปิดพอร์ต 80 บนเครื่องโฮสต์ไปยังพอร์ต 80 ใน Nginx container
    volumes:
      - ./src:/var/www/html # แชร์โค้ดเดียวกันกับ PHP container
      - ./Docker2/nginx_tmp/default.conf:/etc/nginx/conf.d/default.conf   # Mount ไฟล์คอนฟิก Nginx ของคุณ (ถ้ามี)
    depends_on:
      - php # ให้ Nginx รันหลังจาก PHP
    networks:
      - appnet  
    
  phpmyadmin_RQ00002:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_RQ00002
    ports:
      - "8101:80"  # เปิดให้เข้าผ่าน http://localhost:8083
    environment:
      PMA_HOST: db_RQ00002
      PMA_PORT: 3306
    depends_on:
      - db_RQ00002
    networks:
      - appnet  

  db_RQ00002:
    image: mariadb:10.5
    container_name: db_RQ00002
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: test1data
      MYSQL_DATABASE: test1data
      APP_MODE: ${APP_MODE:-dev}
      APP_ENV: ${APP_ENV:-local}
    ports:
      - "3309:3306"  # optional ใช้เปิดจากนอกได้
    volumes:
      - db_RQ00002_data:/var/lib/mysql
      - ./Docker2/db:/docker-entrypoint-initdb.d
    networks:
      - appnet






volumes:
  db_RQ00002_data:

networks:
  appnet:
    driver: bridge
